import { Property } from '@/types/property'

// Two static images for all properties
const propertyImage1 = 'https://www.mckissock.com/wp-content/uploads/2016/11/GettyImages-1151832961.jpg'
const propertyImage2 = 'https://mbluxury1.s3.amazonaws.com/2024/04/17092933/Luxury-Real-Estate-Brands.jpg'

export const mockProperties: Property[] = [
  {
    id: '1',
    address: 'Calle Gran Vía 45, 28013 Madrid',
    latitude: 40.4192,
    longitude: -3.7038,
    neighborhood: 'Centro',
    price: 350000,
    pricePerSqm: 5833,
    size: 60,
    rooms: 2,
    propertyType: 'apartment',
    floor: 3,
    hasElevator: true,
    hasParking: false,
    hasBalcony: true,
    hasTerrace: false,
    hasGarden: false,
    hasSwimmingPool: false,
    hasGym: false,
    hasSecurity: true,
    hasAirConditioning: true,
    hasHeating: true,
    hasFurnished: false,
    hasStorage: true,
    hasConcierge: true,
    hasPetFriendly: false,
    hasWheelchairAccess: true,
    predictedROI: 8.5,
    arbitrageScore: 0.92,
    riskIndicator: 'low',
    clusterId: 'cluster-4',
    clusterLabel: 'Top units in terms of prices',
    images: [
      propertyImage1,
      propertyImage2,
      propertyImage1,
      propertyImage2,
    ],
  },
  {
    id: '2',
    address: 'Avenida de América 12, 28028 Madrid',
    latitude: 40.4342,
    longitude: -3.6708,
    neighborhood: 'Salamanca',
    price: 520000,
    pricePerSqm: 6500,
    size: 80,
    rooms: 3,
    propertyType: 'apartment',
    floor: 5,
    hasElevator: true,
    hasParking: true,
    hasBalcony: true,
    hasTerrace: true,
    hasGarden: false,
    hasSwimmingPool: true,
    hasGym: true,
    hasSecurity: true,
    hasAirConditioning: true,
    hasHeating: true,
    hasFurnished: true,
    hasStorage: true,
    hasConcierge: true,
    hasPetFriendly: true,
    hasWheelchairAccess: true,
    predictedROI: 7.2,
    arbitrageScore: 0.78,
    riskIndicator: 'medium',
    clusterId: 'cluster-3',
    clusterLabel: 'Premium locations',
    images: [
      propertyImage1,
      propertyImage2,
      propertyImage1,
      propertyImage2,
    ],
  },
  {
    id: '3',
    address: 'Calle de la Princesa 89, 28008 Madrid',
    latitude: 40.4286,
    longitude: -3.7142,
    neighborhood: 'Moncloa-Aravaca',
    price: 280000,
    pricePerSqm: 4667,
    size: 60,
    rooms: 2,
    propertyType: 'apartment',
    floor: 2,
    hasElevator: false,
    hasParking: false,
    hasBalcony: true,
    hasTerrace: false,
    hasGarden: false,
    hasSwimmingPool: false,
    hasGym: false,
    hasSecurity: false,
    hasAirConditioning: true,
    hasHeating: true,
    hasFurnished: false,
    hasStorage: false,
    hasConcierge: false,
    hasPetFriendly: true,
    hasWheelchairAccess: false,
    predictedROI: 9.1,
    arbitrageScore: 0.95,
    riskIndicator: 'low',
    clusterId: 'cluster-2',
    clusterLabel: 'High ROI opportunities',
    images: [
      propertyImage1,
      propertyImage2,
      propertyImage1,
      propertyImage2,
    ],
  },
  {
    id: '4',
    address: 'Calle de Alcalá 120, 28009 Madrid',
    latitude: 40.4256,
    longitude: -3.6764,
    neighborhood: 'Retiro',
    price: 450000,
    pricePerSqm: 5625,
    size: 80,
    rooms: 3,
    propertyType: 'apartment',
    floor: 4,
    hasElevator: true,
    hasParking: true,
    hasBalcony: true,
    hasTerrace: true,
    hasGarden: true,
    hasSwimmingPool: false,
    hasGym: false,
    hasSecurity: true,
    hasAirConditioning: true,
    hasHeating: true,
    hasFurnished: false,
    hasStorage: true,
    hasConcierge: false,
    hasPetFriendly: true,
    hasWheelchairAccess: true,
    predictedROI: 7.8,
    arbitrageScore: 0.85,
    riskIndicator: 'medium',
    clusterId: 'cluster-4',
    clusterLabel: 'Top units in terms of prices',
    images: [
      propertyImage1,
      propertyImage2,
      propertyImage1,
      propertyImage2,
    ],
  },
  {
    id: '5',
    address: 'Calle de Serrano 45, 28001 Madrid',
    latitude: 40.4306,
    longitude: -3.6833,
    neighborhood: 'Salamanca',
    price: 680000,
    pricePerSqm: 7556,
    size: 90,
    rooms: 4,
    propertyType: 'apartment',
    floor: 6,
    hasElevator: true,
    hasParking: true,
    hasBalcony: true,
    hasTerrace: true,
    hasGarden: false,
    hasSwimmingPool: true,
    hasGym: true,
    hasSecurity: true,
    hasAirConditioning: true,
    hasHeating: true,
    hasFurnished: true,
    hasStorage: true,
    hasConcierge: true,
    hasPetFriendly: true,
    hasWheelchairAccess: true,
    predictedROI: 6.5,
    arbitrageScore: 0.65,
    riskIndicator: 'high',
    clusterId: 'cluster-3',
    clusterLabel: 'Premium locations',
    images: [
      propertyImage1,
      propertyImage2,
      propertyImage1,
      propertyImage2,
    ],
  },
]

export const mockStats = {
  averagePredictedROI: 7.8,
  activeOpportunities: 1247,
  topPercentileCount: 62,
  averageArbitrageScore: 0.75,
}

